# This is a basic workflow to help you get started with Actions

name: python-yeet

on:
  workflow_dispatch:
    inputs:
      layer_folder:
        type: choice
        description: Repository folder to build
        options:
        - bing
        - bong
        default: bing

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-arm64:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, arm64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Python
        uses: actions/setup-python@v2.3.1
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.8

      # Runs a single command using the runners shell
      - name: Create Package Directory
        run: mkdir -p layer/python
        
      - name: Install Python Dependencies to Directory
        run: pip install azure-identity -t layer/python 

      # Runs a set of commands using the runners shell
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: layer/
          # The desired behavior if no files are found using the provided path.
